name: tmate SSH
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  tmate-ssh:
    runs-on: ubuntu-22.04

    steps:
    - name: Debugging with tmate
      uses: mxschmitt/action-tmate@v3.22
